# Generated by Django 4.1.7 on 2023-05-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_product_slug_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='webapp_Product',
        ),
    ]
