# Generated by Django 4.1.7 on 2023-05-09 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
