# Generated by Django 4.1.7 on 2023-05-09 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='webapp_Product',
        ),
    ]
